package den.ter.money.model

class Valute(
    val AMD: DengiModel,
    val AUD: DengiModel,
    val AZN: DengiModel,
    val BGN: DengiModel,
    val BRL: DengiModel,
    val BYN: DengiModel,
    val CAD: DengiModel,
    val CHF: DengiModel,
    val CNY: DengiModel,
    val CZK: DengiModel,
    val DKK: DengiModel,
    val EUR: DengiModel,
    val GBP: DengiModel,
    val HKD: DengiModel,
    val HUF: DengiModel,
    val INR: DengiModel,
    val JPY: DengiModel,
    val KGS: DengiModel,
    val KRW: DengiModel,
    val KZT: DengiModel,
    val MDL: DengiModel,
    val NOK: DengiModel,
    val PLN: DengiModel,
    val RON: DengiModel,
    val SEK: DengiModel,
    val SGD: DengiModel,
    val TJS: DengiModel,
    val TMT: DengiModel,
    val TRY: DengiModel,
    val UAH: DengiModel,
    val USD: DengiModel,
    val UZS: DengiModel,
    val XDR: DengiModel,
    val ZAR: DengiModel

)